apiVersion: 1

datasources:
  - name: QASL Web3 API
    type: yesoreyeram-infinity-datasource
    uid: qasl-web3-infinity
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      allowedHosts:
        - http://api:7392
